### ISSUE TITLE
Is this how you would implement ewm ops?

### ISSUE THREAD

**Issue by mauropagano** [pdet/Scrooge-McDuck#2]
Hi Pedro,

Is this approach how you would implement exponentially-weighted moving operations (like in [pandas](https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.ewm.html)) in DuckDB?
Currently they could be implemented via `with recursive` but that would be quite slow.

Sorry about opening it as issue, not sure how else to get in touch, ofc please feel free to close immediately

**Comment by pdet** [comment]
Hi @mauropagano 

By having a quick look at it, it does look like something you can implement as a defined function in DuckDB.

Im currently working on a scaffolding project for DuckDB extensions to facilitate its development by users. So I can keep you posted on that (it will take a little while still though :-) )

Otherwise you can take this project as an example!

**Comment by mauropagano** [comment]
The scaffolding project sounds great and yeah I’d love to give it go when ready!

**Comment by pdet** [comment]
Hi @mauropagano 

Just in case you missed it,

we released the boilerplate repo for the duckdb extensions:
https://github.com/duckdb/extension-template

There is also a short presentation about it available online: 
https://www.youtube.com/watch?v=UKo_LQyLTko&ab_channel=DuckDBLabs
